### ISSUE TITLE
out dated peerDependencies

### ISSUE THREAD

**Issue by gomjellie** [pqina/filepond-plugin-image-exif-orientation#1]
i got this warning when installing via npm

`npm WARN filepond-plugin-image-exif-orientation@1.0.2 requires a peer of filepond@^1.8.0 but none is installed. You must install peer dependencies yourself.
`

[package.json](https://github.com/pqina/filepond-plugin-image-exif-orientation/blob/master/package.json) 
be cause it has dependency filepond@1.8.0

but filepond-plugin-image-preview@3.1.1 requires a peer of filepond@^3.0.0 and 
react-filepond@5.0.0 also requires a peer of filepond@^3.0.0

i guess it needs to be update peer dependency version to 3.0.0

**Comment by rikschennink** [comment]
I've just updated the package to `1.0.3`, peer dependency is now at `3.0.0`, should fix the issue.
