### ISSUE TITLE
The preview plugin still shows wrong orientation when using in React app and image was restored from the server

### ISSUE THREAD

**Issue by dnknitro** [pqina/filepond-plugin-image-exif-orientation#2]
This is my React app code:
```
import 'filepond/dist/filepond.min.css';
import 'filepond-plugin-image-preview/dist/filepond-plugin-image-preview.min.css';
import { FilePond, registerPlugin } from 'react-filepond';
import FilePondPluginImageExifOrientation from 'filepond-plugin-image-exif-orientation';
import FilePondPluginImagePreview from 'filepond-plugin-image-preview';
import FilePondPluginFileMetadata from 'filepond-plugin-file-metadata';

registerPlugin(FilePondPluginImageExifOrientation, FilePondPluginImagePreview, FilePondPluginFileMetadata);
```
If I upload the image - it is orientated correctly. However if I restore existing image using addFiles method - it is orientated incorrectly.
![2019-04-29_20 25 30](https://user-images.githubusercontent.com/5778863/56936443-0e224180-6abd-11e9-91fb-b7d6bd2b5504.png)

**Comment by rikschennink** [comment]
Tried to reproduce this using the PHP boilerplate project. Tried with `files` property and `addFiles` method, both resulted in the correct image orientation. Will close for now.
